- cpf-core/src/pt/webdetails/cpf/localization/MessageBundlesHelper.java
- cpf-core/src/pt/webdetails/cpf/repository/api/FileAccess.java
- cpf-core/src/pt/webdetails/cpf/repository/api/IACAccess.java
- cpf-core/src/pt/webdetails/cpf/repository/api/IBasicFile.java
- cpf-core/src/pt/webdetails/cpf/repository/api/IBasicFileFilter.java
- cpf-core/src/pt/webdetails/cpf/repository/api/IContentAccessFactory.java
- cpf-core/src/pt/webdetails/cpf/repository/api/IRWAccess.java
- cpf-core/src/pt/webdetails/cpf/repository/api/IReadAccess.java
- cpf-core/src/pt/webdetails/cpf/repository/api/IUserContentAccess.java
- cpf-core/src/pt/webdetails/cpf/repository/impl/FileBasedResourceAccess.java
- cpf-core/test-src/pt/webdetails/cpf/localization/test/PluginWriteAccess.java
- cpf-pentaho-base/src/pt/webdetails/cpf/repository/pentaho/SystemPluginResourceAccess.java
- cpf-pentaho/src/pt/webdetails/cpf/repository/pentaho/PentahoLegacySolutionAccess.java
- cpf-pentaho/src/pt/webdetails/cpf/repository/pentaho/PentahoLegacyUserContentAccess.java
- cpf-pentaho/src/pt/webdetails/cpf/repository/pentaho/PluginLegacySolutionResourceAccess.java
- cpf-pentaho/test-src/pt/webdetails/cpf/repository/pentaho/repository/PentahoLegacySolutionAccessTest.java
- cpf-pentaho5/src/pt/webdetails/cpf/repository/pentaho/unified/PluginRepositoryResourceAccess.java
- cpf-pentaho5/src/pt/webdetails/cpf/repository/pentaho/unified/UnifiedRepositoryAccess.java
- cpf-pentaho5/src/pt/webdetails/cpf/repository/pentaho/unified/UserContentRepositoryAccess.java
> Cde 442 The CDE folder that gets created under public should be hidden

- cpf-pentaho-base/src/pt/webdetails/cpf/persistence/PersistenceEngine.java
- Include id in returned JSON object to avoid throwing exceptions on updates
> [CDE-447] - ViewManager custom component fails to save/load views

- build-res/subfloor.xml
- cpf-core/test-resources/cpkSol/build-res/subfloor.xml
- cpf-pentaho/test-resources/repo/system/cpkSol/build-res/subfloor.xml
Merge of master into future-develop
> Auto-Merge refreshing development branch

- cpf-pentaho/pom.xml
with those maintained by the build team.
@lucboudreau @lgrill-pentaho
> [CLEANUP] making version properties consistent

- core/src/test/java/pt/webdetails/cpf/localization/MessageBundlesHelperTest.java
@pamval please check. Checkstyle was updated last week
> [CHECKSTYLE] - Cleaning up check style errors

- pentaho/src/main/java/pt/webdetails/cpf/SecurityAssertions.java
- pentaho/src/main/java/pt/webdetails/cpf/SimpleContentGenerator.java
- pentaho/src/main/java/pt/webdetails/cpf/session/PentahoSession.java
- pentaho/src/main/java/pt/webdetails/cpf/web/CpfServletContext.java
- pom.xml
This is part of a set of pull requests for the spring 4 upgrade work:
https://github.com/pentaho/pentaho-platform/pull/3104
https://github.com/webdetails/cpf/pull/98
https://github.com/webdetails/cdf/pull/870
https://github.com/webdetails/cda/pull/209
https://github.com/webdetails/cde/pull/718
https://github.com/pentaho/data-access/pull/783
https://github.com/pentaho/pentaho-reporting/pull/828
https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/436
https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/842
https://github.com/pentaho/marketplace/pull/115
https://github.com/pentaho/big-data-plugin/pull/739
https://github.com/pentaho/pentaho-platform-ee/pull/972
https://github.com/pentaho/pentaho-platform-plugin-interactive-reporting/pull/477 …
> [BACKLOG-10623] Upgrade Spring security / framework

- core/src/main/java/pt/webdetails/cpf/PluginSettings.java
- core/src/main/java/pt/webdetails/cpf/utils/XmlDom4JUtils.java
- core/src/main/java/pt/webdetails/cpf/utils/XmlParserFactoryProducer.java
- pentaho/src/main/java/pt/webdetails/cpf/VersionChecker.java
@pamval, @mbatchelor, could you please take a look?
> [PPP-3506] - XXE Security Vulnerability in xml parsers

- core/pom.xml
- pentaho/pom.xml
- pom.xml
subject to merge of https://github.com/pentaho/pentaho-commons-json/pull/8
> [ENGOPS-2639] json GAV change

- .gitignore
- pom.xml
> [ENGOPS-3027] update parent pom version to 7.1-SNAPSHOT

- pom.xml
@pamval Fixes checkstyle reports picking up the wrong configuration
> [CLEANUP] Removing deprecated report configuration

- core/src/test/resources/cpkSol/README.md
- core/src/test/resources/cpkSol/build-res/subfloor.xml
WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!
> [ENGOPS-3650] change Pentaho to Hitachi Vantara and update copyright date

- core/src/test/resources/cpkSol/build.properties
- core/src/test/resources/cpkSol/ivy.xml
- pentaho/pom.xml
- pom.xml
WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!
> [ENGOPS-1757] version name consolidation

- pom.xml
@davidmsantos90 @webdetails/millenniumfalcon  please review
> [BACKLOG-21719] - Update jaxen version

- core/src/main/java/pt/webdetails/cpf/utils/MimeTypes.java
@webdetails/millenniumfalcon please review
> [BACKLOG-22048] Foundry CT2000 Dashboard

- pentaho/src/main/java/pt/webdetails/cpf/InterPluginCall.java
@webdetails/millenniumfalcon please review
Merge before:
- https://github.com/webdetails/cpk/pull/68
> [BACKLOG-23575] Pentaho App Builder is broken due to invalid bean id call

- assemblies/cpf-pdi/pom.xml
- core/pom.xml
- core/src/main/java/pt/webdetails/cpf/PluginSettings.java
- core/src/test/java/pt/webdetails/cpf/PluginSettingsTest.java
- pentaho/pom.xml
- pentaho/src/main/java/pt/webdetails/cpf/plugins/Plugin.java
- pentaho/src/test/java/pt/webdetails/cpf/plugins/PluginTest.java
- pom.xml
This is one of a series of PRs. See pentaho/maven-parent-poms#70 for the complete list and more details. **Do not merge until further notice!**
@graimundo
> [PPP-4182] Use of vulnerable component dom4j-1.6.1.jar  CVE-2018-1000632

- pentaho/src/main/java/pt/webdetails/cpf/olap/OlapApi.java
> [CDA-210] OlapApi methods in CPF should not be void methods

- pentaho/src/main/java/pt/webdetails/cpf/InterPluginCall.java
- pentaho/src/test/java/pt/webdetails/cpf/InterPluginCallTest.java
Changed InterPluginCall response treatment, to manage javax.ws.rs.core.Response
Checkstyle corrections
SonarLint broken rules fixes
Unit tests for InterPluginCall
> [CDF-962] - CpkApi methods in Cpk should not be void - warnings in console

- pentaho/pom.xml
- pom.xml
> [BACKLOG-27566] Centralize SLF4J dependency

- pom.xml
- rca/pom.xml
[BACKLOG-27567] Centralize org.osgi dependencies management
[BACKLOG-27578] Use parent pom centralized profile for feature generation
@graimundo
> [BACKLOG-27567] Centralize org.osgi dependencies management

- core/src/main/java/pt/webdetails/cpf/PluginEnvironment.java
- core/src/main/java/pt/webdetails/cpf/packager/DependenciesPackage.java
- core/src/main/java/pt/webdetails/cpf/packager/dependencies/FileDependency.java
- pentaho/src/main/java/pt/webdetails/cpf/PentahoBasePluginEnvironment.java
- pentaho/src/main/java/pt/webdetails/cpf/SimpleLifeCycleListener.java
@webdetails/millenniumfalcon please review
Merge before -> https://github.com/webdetails/cde/pull/933
> [CDE-1001][CLEANUP] Legacy components are not being handled as expected

- core/src/main/java/pt/webdetails/cpf/PluginEnvironment.java
- core/src/main/java/pt/webdetails/cpf/packager/DependenciesPackage.java
- core/src/main/java/pt/webdetails/cpf/packager/dependencies/FileDependency.java
- pentaho/src/main/java/pt/webdetails/cpf/PentahoBasePluginEnvironment.java
- pentaho/src/main/java/pt/webdetails/cpf/SimpleLifeCycleListener.java
> [SP-5100] cleanups

- core/src/main/java/pt/webdetails/cpf/PluginEnvironment.java
- core/src/main/java/pt/webdetails/cpf/packager/DependenciesPackage.java
- core/src/main/java/pt/webdetails/cpf/packager/dependencies/FileDependency.java
- pentaho/src/main/java/pt/webdetails/cpf/PentahoBasePluginEnvironment.java
- pentaho/src/main/java/pt/webdetails/cpf/SimpleLifeCycleListener.java
@webdetails/millenniumfalcon @pamval @pentaho-lmartins please review
Cherrypick from: https://github.com/webdetails/cpf/pull/145 and https://github.com/webdetails/cpf/pull/146
> [CLEANUP] Code cleanup and license headers updated

- pentaho/src/main/java/pt/webdetails/cpf/SimpleContentGenerator.java
- pentaho/src/main/java/pt/webdetails/cpf/audit/CpfAuditHelper.java
@bennychow please review
/cc @jcarneirohv
> [BISERVER-5014] Setting MDC instanceId in startAudit and setting instanceId in SimpleContentGenerator

- core/pom.xml
- core/src/main/java/pt/webdetails/cpf/packager/DependenciesPackage.java
- core/src/test/java/pt/webdetails/cpf/packager/DependenciesPackageTest.java
- pom.xml
@ssamora, @smmribeiro please review and merge.
Merge along with https://github.com/webdetails/cde/pull/993.
> [PPP-4690] XSS on pentaho-cdf-dd/api/renderer/render?root parameter

- core/src/main/resources/pt/webdetails/cpf/persistence/orient.xml
- pentaho/pom.xml
- pentaho/src/test/java/pt/webdetails/cpf/persistence/PersistenceEngineForTests.java
- pom.xml
@smmribeiro 
@andreramos89 
@renato-s 
@ricksjames
> [BACKLOG-35397] - Fix integration tests for cpf project to run in both Java 11 and Java 8

- core/pom.xml
- core/src/main/java/pt/webdetails/cpf/packager/DependenciesPackage.java
- core/src/test/java/pt/webdetails/cpf/packager/DependenciesPackageTest.java
- pom.xml
@webdetails/sp-branch-write please review and merge.
> [SP-6094] Backport of PPP-4690 - XSS on pentaho-cdf-dd/api/renderer/render?root parameter

- core/pom.xml
- core/src/main/java/pt/webdetails/cpf/packager/DependenciesPackage.java
- core/src/test/java/pt/webdetails/cpf/packager/DependenciesPackageTest.java
- pom.xml
@webdetails/sp-branch-write please review and merge.
> [SP-6095] Backport of PPP-4690 - XSS on pentaho-cdf-dd/api/renderer/render?root parameter

- pom.xml
[PPP-4865] Vulnerable Component: snakeyaml
[PPP-4865]: https://hv-eng.atlassian.net/browse/PPP-4865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-4865] Vulnerable Component: snakeyaml

- pentaho/pom.xml
- pom.xml
> [PPP-4865] - Vulnerable Component: snakeyaml

- pentaho-rca/pom.xml
- pentaho-rca/src/main/java/pt/webdetails/cpf/repository/rca/RemoteReadAccess.java
- pentaho-rca/src/main/java/pt/webdetails/cpf/repository/rca/RemoteReadWriteAccess.java
- pentaho-rca/src/main/java/pt/webdetails/cpf/repository/rca/RemoteUserContentAccess.java
- pentaho/pom.xml
- pom.xml
- rca/pom.xml
[BACKLOG-41601]-Upgrade sun jersey from 1.x to glassfish jersey 2.x
[BACKLOG-41601]: https://hv-eng.atlassian.net/browse/BACKLOG-41601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-41601]-Upgrade sun jersey from 1.x to glassfish jersey 2.x

- osgi/pom.xml
- pentaho/pom.xml
- pom.xml
…][PPP-4967] Karaf upgrade to 4.4.6 and vulnerability fixes
(cherry picked from commit a7e812a3511dc7b8d453d3ceaceee1583e9895b3)
[PPP-4967]: https://hv-eng.atlassian.net/browse/PPP-4967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SP-6671][SP-6667][SP-6668][SP-6669][SP-6670][SP-6672][SP-6673][SP-6674] Back port of Karaf 4.4.6 upgrade and security vulnerability fixes

- assemblies/cpf-pdi/pom.xml
@webdetails/millenniumfalcon please review
Original [commit](https://github.com/webdetails/cpf/commit/07846def7971e92dae700f533ad99130be8b2ffd)
Merge together with https://github.com/pentaho/pentaho-det-ee/pull/697
> [SP-6688] Backport of PPP-5167 - End-of-Life: AngularJS 1.8.0  Pentaho Data Integration - Move DET into a addon or a kar file (10.2 Suite)

- assemblies/cpf-pdi/pom.xml
- assemblies/cpf-rca/pom.xml
- assemblies/cpf/pom.xml
[BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures
[BACKLOG-43874]: https://hv-eng.atlassian.net/browse/BACKLOG-43874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures

- core/pom.xml
- pentaho/pom.xml
- pom.xml
Removed several hard-coded versions - use what comes from parent pom
> feat[PPP-5649]: upgrade commons-io
